export const scienceQuestionBankDemo = {
  documentId: "qb_pdf_State_Board_science",
  examName: "Board Exam",
  year: "2023",
  board: "State Board",
  classNumber: "10",
  subject: "Science",
  subjectGroupKey: "science",
  unitName: "Science",
  totalQuestions: 34,
  difficultyDistribution: {
    easy: 17,
    medium: 14,
    hard: 3,
  },
  questions: [
    {
      question_id: "48762fba72fe",
      question: "1. Light year is the unit of _______",
      marks: 1,
      type: "mcq",
      options: ["distance", "time", "density", "Both length and time"],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Units of measurement",
      unit_number: 1,
      section_title: "Measuring larger distances",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "d57013af1611",
      question: "2. Density of water is _______",
      marks: 1,
      type: "mcq",
      options: ["800 kg/m3", "1000 kg/m3", "7800 kg/m3", "8000 kg/m3"],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Density of water",
      unit_number: 1,
      section_title: "Density",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "efa7ddf80382",
      question: "3. A particle is moving in a circular path of radius r. The displacement after half a circle would be _______",
      marks: 1,
      type: "mcq",
      options: ["Zero", "R", "2r", "r/2"],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "analyze",
      topic: "Displacement in circular motion",
      unit_number: 2,
      section_title: "Evaluation",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "f315ea2dc17c",
      question: "4. The metal which is liquid at room temperature is _______",
      marks: 1,
      type: "mcq",
      options: ["Chlorine", "Sulphur", "Mercury", "Silver"],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Properties of metals",
      unit_number: 3,
      section_title: "Metals",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "a2cb98c1d84e",
      question: "5. Which one of the following is an example for a metal?",
      marks: 1,
      type: "mcq",
      options: ["Iron", "Oxygen", "Helium", "Water"],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Classification of elements",
      unit_number: 3,
      section_title: "Metals",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "58a933f608c0",
      question: "6. _______ is positively charged.",
      marks: 1,
      type: "mcq",
      options: ["Proton", "Electron", "Molecule", "Neutron"],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Sub-atomic particles",
      unit_number: 4,
      section_title: "Proton (p)",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "6623f60f87d1",
      question: "7. Asexual reproduction in yeast is _______",
      marks: 1,
      type: "mcq",
      options: ["Spore formation", "Fragmentation", "Pollination", "Budding"],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Types of asexual reproduction",
      unit_number: 5,
      section_title: "Asexual reproduction",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "dfb22274ed68",
      question: "8. Climbing roots are seen in _______",
      marks: 1,
      type: "mcq",
      options: ["Betel", "Back pepper", "Both of them", "None of them"],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Climbing roots in plants",
      unit_number: 5,
      section_title: "Modifications of plant parts",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "0488ae375eb9",
      question: "9. Tobacco chewing causes _______",
      marks: 1,
      type: "mcq",
      options: ["Anemia", "Periodontitis", "Tuberculosis", "Pneumonia"],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Effects of tobacco chewing",
      unit_number: 6,
      section_title: "Evaluation",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "3a5e1ab9a33e",
      question: "10. Which technology uses pixels to create pictures?",
      marks: 1,
      type: "mcq",
      options: ["Vector", "Raster", "Both", "None"],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Types of image technology",
      unit_number: 7,
      section_title: "Choose the correct answer.",
      question_type_refined: "mcq",
      estimated_time_minutes: 2,
    },
    {
      question_id: "be866bdd53f0",
      question: "11. What is Centre of Gravity? _______",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Centre of Gravity",
      unit_number: 2,
      section_title: "Centre of Gravity",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "d10b2c9eaefd",
      question: "12. An athlete takes 25 seconds to complete a 200m Sprint event. Find her speed? _______",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Speed Calculation",
      unit_number: 2,
      section_title: "DO YOU KNOW?",
      question_type_refined: "numerical",
      estimated_time_minutes: 2,
    },
    {
      question_id: "fdd67eee2906",
      question: "13. What are derived Quantities? _______",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Derived Quantities",
      unit_number: 1,
      section_title: "Fundamental Quantities and Derived Quantities",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "38ba94297fec",
      question: "14. Define - Astronomical unit. _______",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Astronomical Unit",
      unit_number: 1,
      section_title: "Measuring larger distances",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "a292a16672bb",
      question: "15. Fill in the Blanks.\na) The rate of change of velocity is _______\nb) Elements are made up of _______ kinds of atoms.",
      marks: 2,
      type: "fill_in_the_blanks",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Acceleration and Composition of Elements",
      unit_number: 2,
      section_title: "DO YOU KNOW?",
      question_type_refined: "fill_in_the_blanks",
      estimated_time_minutes: 2,
    },
    {
      question_id: "39388b88deb7",
      question: "16. Write the Symbols for the following elements.\na) Aluminium\nb) Carbon\nc) Mercury\nd) Helium",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Chemical Symbols",
      unit_number: 3,
      section_title: "Elements (includes Classification of Elements and Symbol of an element)",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "9625c73a1ba6",
      question: "17. State True or False, if false give correct Statement.\ni) Two different elements may have similar atoms.\nii) Argon is mono atomic Gas.",
      marks: 2,
      type: "true_or_false",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "evaluate",
      topic: "True or False Statements",
      unit_number: 4,
      section_title: "Evaluation",
      question_type_refined: "true_or_false",
      estimated_time_minutes: 2,
    },
    {
      question_id: "3a6b46db1950",
      question: "18. What are elements? Give two Examples.",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Elements",
      unit_number: 3,
      section_title: "Elements",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "7b705874b472",
      question: "19. Match the following.\na) Valancy - Proton\nb) Neutral Particle - Electron in the outermost orbit\nc) Hydrogen - Neutron\nd) Positively charged particle - Monovalent",
      marks: 2,
      type: "match_the_following",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "analyze",
      topic: "Matching Concepts",
      unit_number: 4,
      section_title: "Match the following",
      question_type_refined: "match_the_following",
      estimated_time_minutes: 2,
    },
    {
      question_id: "bf1ba3f4e092",
      question: "20. Name the sub-atomic particles.",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Sub-atomic Particles",
      unit_number: 4,
      section_title: "The sub-atomic particles",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "963a6294f831",
      question: "21. Differentiate mass numbers from atomic Number.",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Differentiation of mass number and atomic number",
      unit_number: 4,
      section_title: "Evaluation",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "a1946f1fef92",
      question: "22. Ginger is considered to be a Stem, not a Root why?",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Identification of plant parts",
      unit_number: 5,
      section_title: "Modifications of plant parts",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "896aaf7dfd8b",
      question: "23. What is Cross Pollination?",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Definition of cross pollination",
      unit_number: 5,
      section_title: "Pollination (continued)",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "d8d839e5f548",
      question: "24. What are the two important parts of a flower?",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Parts of a flower",
      unit_number: 5,
      section_title: "Sexual reproduction",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "49a8f1d0932a",
      question: "25. Analogy:\ni) Typhoid : Bacteria :: Hepatitis :\nii) Tuberculosis : Air :: cholera :",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Analogy of diseases",
      unit_number: 6,
      section_title: "Diseases",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "2c880b99b979",
      question: "26. Give any two communicable diseases, which spread in your locality during monsoon.",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Identification of communicable diseases",
      unit_number: 6,
      section_title: "Diseases",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "d9d212ce00bf",
      question: "27. What steps you will follow to keep yours teeth healthy?",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Dental hygiene practices",
      unit_number: 6,
      section_title: "Care of the body",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "8bf4c039d987",
      question: "28. What is Raster Graphics?",
      marks: 2,
      type: "short_answer",
      options: [],
      correct_answer: "",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Definition of raster graphics",
      unit_number: 7,
      section_title: "Evaluation",
      question_type_refined: "short_answer",
      estimated_time_minutes: 2,
    },
    {
      question_id: "df02e2ff1374",
      question: "29. How will you determine the density of a Stone using a measuring Jar?",
      marks: 5,
      type: "long_answer",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Determining density using a measuring jar",
      unit_number: 1,
      section_title: "X. Answer in detail.",
      question_type_refined: "long_answer",
      estimated_time_minutes: 5,
    },
    {
      question_id: "28abd8d092a4",
      question: "30. Write about the experiment to find the centre of gravity of the irregularly-shaped plate.",
      marks: 5,
      type: "long_answer",
      options: [],
      correct_answer: "",
      difficulty: "hard",
      bloom_level: "analyze",
      topic: "Experiment to find the centre of gravity",
      unit_number: 2,
      section_title: "Centre of Gravity",
      question_type_refined: "long_answer",
      estimated_time_minutes: 5,
    },
    {
      question_id: "8adeaad38d46",
      question: "31. Differentiate between elements and compounds.",
      marks: 5,
      type: "long_answer",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "analyze",
      topic: "Differentiation between elements and compounds",
      unit_number: 3,
      section_title: "Section: Evaluation",
      question_type_refined: "long_answer",
      estimated_time_minutes: 5,
    },
    {
      question_id: "d685f3dc64d6",
      question: "32. The atomic number and the mass number of an element is 26 and 56 respectively. Calculate the numbers of electrons, protons and Neutrons in its atom. Draw the structure.",
      marks: 5,
      type: "long_answer",
      options: [],
      correct_answer: "",
      difficulty: "hard",
      bloom_level: "apply",
      topic: "Calculation of subatomic particles",
      unit_number: 4,
      section_title: "Section: 4.3 Atomic number and Mass number",
      question_type_refined: "long_answer",
      estimated_time_minutes: 5,
    },
    {
      question_id: "da0a37a7be26",
      question: "33. Write a brief account on Pollination.",
      marks: 5,
      type: "long_answer",
      options: [],
      correct_answer: "",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Pollination in plants",
      unit_number: 5,
      section_title: "Section: Pollination (continued)",
      question_type_refined: "long_answer",
      estimated_time_minutes: 5,
    },
    {
      question_id: "3f8c8cdf6c5f",
      question: "34. List the Situations in which first aid is given, what would you do if a person suffers from skin burns.",
      marks: 5,
      type: "long_answer",
      options: [],
      correct_answer: "",
      difficulty: "hard",
      bloom_level: "evaluate",
      topic: "First aid procedures",
      unit_number: 6,
      section_title: "Section: 6.5 Safety and First Aid",
      question_type_refined: "long_answer",
      estimated_time_minutes: 5,
    },
  ],
};

type DemoQuestionInput = {
  question_id: string;
  question: string;
  marks: number;
  type: string;
  options?: string[];
  difficulty: string;
  bloom_level: string;
  topic: string;
  unit_number: number;
  section_title: string;
  question_type_refined: string;
  estimated_time_minutes?: number;
};

const makeDemoQuestion = (q: DemoQuestionInput) => ({
  options: [],
  correct_answer: "",
  estimated_time_minutes: q.marks >= 5 ? 5 : 2,
  ...q,
});

// TEMP DEMO CHANGE: Local Maths Class 10 question paper until DB JSON upload is available.
export const mathsQuestionBankDemo = {
  documentId: "qb_pdf_State_Board_maths",
  examName: "Board Exam",
  year: "2023",
  board: "State Board",
  classNumber: "10",
  subject: "Mathematics",
  subjectGroupKey: "maths",
  unitName: "Mathematics",
  totalQuestions: 25,
  difficultyDistribution: {
    easy: 10,
    medium: 11,
    hard: 4,
  },
  questions: [
    makeDemoQuestion({
      question_id: "math10_001",
      question: "1. The HCF of 96 and 404 is _______",
      marks: 1,
      type: "mcq",
      options: ["2", "4", "8", "12"],
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Real numbers",
      unit_number: 1,
      section_title: "Real Numbers",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "math10_002",
      question: "2. If the zeroes of x^2 - 5x + 6 are alpha and beta, then alpha + beta is _______",
      marks: 1,
      type: "mcq",
      options: ["5", "6", "-5", "-6"],
      difficulty: "easy",
      bloom_level: "understand",
      topic: "Polynomials",
      unit_number: 2,
      section_title: "Polynomials",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "math10_003",
      question: "3. The pair of equations x + y = 5 and x - y = 1 has the solution _______",
      marks: 1,
      type: "mcq",
      options: ["x = 3, y = 2", "x = 2, y = 3", "x = 4, y = 1", "x = 1, y = 4"],
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Pair of linear equations",
      unit_number: 3,
      section_title: "Pair of Linear Equations",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "math10_004",
      question: "4. The discriminant of 2x^2 - 4x + 3 = 0 is _______",
      marks: 1,
      type: "mcq",
      options: ["-8", "8", "16", "40"],
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Quadratic equations",
      unit_number: 4,
      section_title: "Quadratic Equations",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "math10_005",
      question: "5. The 10th term of the arithmetic progression 3, 7, 11, 15, ... is _______",
      marks: 1,
      type: "mcq",
      options: ["35", "39", "43", "47"],
      difficulty: "easy",
      bloom_level: "apply",
      topic: "Arithmetic progressions",
      unit_number: 5,
      section_title: "Arithmetic Progressions",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "math10_006",
      question: "6. In a right triangle, if sin A = 3/5, then cos A is _______",
      marks: 1,
      type: "mcq",
      options: ["4/5", "5/4", "3/4", "5/3"],
      difficulty: "easy",
      bloom_level: "understand",
      topic: "Trigonometry",
      unit_number: 8,
      section_title: "Introduction to Trigonometry",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "math10_007",
      question: "7. The distance of the point (3, 4) from the origin is _______",
      marks: 1,
      type: "mcq",
      options: ["3 units", "4 units", "5 units", "7 units"],
      difficulty: "easy",
      bloom_level: "apply",
      topic: "Coordinate geometry",
      unit_number: 7,
      section_title: "Coordinate Geometry",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "math10_008",
      question: "8. The area of a circle with radius 7 cm is _______",
      marks: 1,
      type: "mcq",
      options: ["44 cm2", "154 cm2", "308 cm2", "49 cm2"],
      difficulty: "easy",
      bloom_level: "apply",
      topic: "Areas related to circles",
      unit_number: 12,
      section_title: "Areas Related to Circles",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "math10_009",
      question: "9. Find the LCM of 12, 18 and 30 using prime factorisation.",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "apply",
      topic: "Real numbers",
      unit_number: 1,
      section_title: "Real Numbers",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_010",
      question: "10. Find a quadratic polynomial whose zeroes are 2 and -3.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Polynomials",
      unit_number: 2,
      section_title: "Polynomials",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_011",
      question: "11. Solve the equations: 2x + 3y = 13 and x - y = 1.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Pair of linear equations",
      unit_number: 3,
      section_title: "Pair of Linear Equations",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_012",
      question: "12. Find the roots of x^2 - 7x + 10 = 0 by factorisation.",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "apply",
      topic: "Quadratic equations",
      unit_number: 4,
      section_title: "Quadratic Equations",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_013",
      question: "13. Find the sum of the first 20 terms of the AP 5, 8, 11, 14, ...",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Arithmetic progressions",
      unit_number: 5,
      section_title: "Arithmetic Progressions",
      question_type_refined: "numerical",
    }),
    makeDemoQuestion({
      question_id: "math10_014",
      question: "14. State and prove the Basic Proportionality Theorem for a triangle.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Triangles",
      unit_number: 6,
      section_title: "Triangles",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_015",
      question: "15. Find the midpoint of the line segment joining (2, -3) and (6, 5).",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "apply",
      topic: "Coordinate geometry",
      unit_number: 7,
      section_title: "Coordinate Geometry",
      question_type_refined: "numerical",
    }),
    makeDemoQuestion({
      question_id: "math10_016",
      question: "16. Prove that 1 + tan^2 A = sec^2 A.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Trigonometric identities",
      unit_number: 8,
      section_title: "Introduction to Trigonometry",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_017",
      question: "17. From a point 20 m away from the foot of a tower, the angle of elevation of the top is 30 degrees. Find the height of the tower.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Heights and distances",
      unit_number: 9,
      section_title: "Applications of Trigonometry",
      question_type_refined: "numerical",
    }),
    makeDemoQuestion({
      question_id: "math10_018",
      question: "18. A chord of a circle is 12 cm long and its distance from the centre is 8 cm. Find the radius of the circle.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Circles",
      unit_number: 10,
      section_title: "Circles",
      question_type_refined: "numerical",
    }),
    makeDemoQuestion({
      question_id: "math10_019",
      question: "19. Construct a tangent to a circle of radius 3 cm from a point 5 cm away from its centre.",
      marks: 2,
      type: "short_answer",
      difficulty: "hard",
      bloom_level: "create",
      topic: "Constructions",
      unit_number: 11,
      section_title: "Constructions",
      question_type_refined: "construction",
    }),
    makeDemoQuestion({
      question_id: "math10_020",
      question: "20. A bag contains 5 red balls, 3 blue balls and 2 green balls. Find the probability of drawing a blue ball.",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "apply",
      topic: "Probability",
      unit_number: 15,
      section_title: "Probability",
      question_type_refined: "numerical",
    }),
    makeDemoQuestion({
      question_id: "math10_021",
      question: "21. Solve by using the quadratic formula: 3x^2 - 5x - 2 = 0.",
      marks: 5,
      type: "long_answer",
      difficulty: "medium",
      bloom_level: "apply",
      topic: "Quadratic equations",
      unit_number: 4,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_022",
      question: "22. Prove that two triangles are similar if their corresponding sides are proportional. Apply it to find the unknown side when triangle ABC is similar to triangle PQR, AB = 6 cm, BC = 8 cm, PQ = 9 cm and QR is unknown.",
      marks: 5,
      type: "long_answer",
      difficulty: "hard",
      bloom_level: "analyze",
      topic: "Triangles",
      unit_number: 6,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_023",
      question: "23. The angle of elevation of the top of a building from the foot of a tower is 30 degrees and the angle of elevation of the top of the tower from the foot of the building is 60 degrees. If the tower is 30 m high, find the height of the building.",
      marks: 5,
      type: "long_answer",
      difficulty: "hard",
      bloom_level: "analyze",
      topic: "Applications of trigonometry",
      unit_number: 9,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_024",
      question: "24. A solid is in the form of a cylinder surmounted by a cone. The radius is 7 cm, the height of the cylinder is 20 cm and the height of the cone is 24 cm. Find the total surface area.",
      marks: 5,
      type: "long_answer",
      difficulty: "hard",
      bloom_level: "apply",
      topic: "Surface areas and volumes",
      unit_number: 13,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
    makeDemoQuestion({
      question_id: "math10_025",
      question: "25. The marks of 30 students are grouped in class intervals. Explain the steps to find the mean by the assumed mean method and calculate it for a suitable frequency table.",
      marks: 5,
      type: "long_answer",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Statistics",
      unit_number: 14,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
  ],
};

// TEMP DEMO CHANGE: Local Social Science Class 10 question paper until DB JSON upload is available.
export const socialQuestionBankDemo = {
  documentId: "qb_pdf_State_Board_social",
  examName: "Board Exam",
  year: "2023",
  board: "State Board",
  classNumber: "10",
  subject: "Social Science",
  subjectGroupKey: "social",
  unitName: "Social Science",
  totalQuestions: 25,
  difficultyDistribution: {
    easy: 11,
    medium: 10,
    hard: 4,
  },
  questions: [
    makeDemoQuestion({
      question_id: "soc10_001",
      question: "1. The Non-Cooperation Movement was launched in the year _______",
      marks: 1,
      type: "mcq",
      options: ["1919", "1920", "1922", "1930"],
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Indian nationalism",
      unit_number: 1,
      section_title: "History: Nationalism in India",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "soc10_002",
      question: "2. The main occupation in the primary sector is _______",
      marks: 1,
      type: "mcq",
      options: ["Banking", "Agriculture", "Teaching", "Transport"],
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Sectors of economy",
      unit_number: 5,
      section_title: "Economics: Sectors of the Indian Economy",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "soc10_003",
      question: "3. Black soil is most suitable for growing _______",
      marks: 1,
      type: "mcq",
      options: ["Cotton", "Tea", "Rubber", "Jute"],
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Soils and agriculture",
      unit_number: 3,
      section_title: "Geography: Resources and Development",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "soc10_004",
      question: "4. Power is shared among legislature, executive and judiciary under _______",
      marks: 1,
      type: "mcq",
      options: ["Federal division", "Horizontal division", "Community government", "Coalition government"],
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Power sharing",
      unit_number: 4,
      section_title: "Civics: Power Sharing",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "soc10_005",
      question: "5. The Reserve Bank of India supervises the formal sources of _______",
      marks: 1,
      type: "mcq",
      options: ["Credit", "Farming", "Irrigation", "Transport"],
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Money and credit",
      unit_number: 6,
      section_title: "Economics: Money and Credit",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "soc10_006",
      question: "6. The first printed books in China were produced by _______",
      marks: 1,
      type: "mcq",
      options: ["Hand printing", "Woodblock printing", "Lithography", "Offset printing"],
      difficulty: "medium",
      bloom_level: "remember",
      topic: "Print culture",
      unit_number: 2,
      section_title: "History: Print Culture",
      question_type_refined: "mcq",
    }),
    makeDemoQuestion({
      question_id: "soc10_007",
      question: "7. Fill in the blank: Belgium followed a model of _______ to reduce social conflict.",
      marks: 1,
      type: "fill_in_the_blanks",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Power sharing",
      unit_number: 4,
      section_title: "Civics: Power Sharing",
      question_type_refined: "fill_in_the_blanks",
    }),
    makeDemoQuestion({
      question_id: "soc10_008",
      question: "8. State whether the statement is true or false: Human development includes health, education and income.",
      marks: 1,
      type: "true_or_false",
      difficulty: "easy",
      bloom_level: "understand",
      topic: "Development",
      unit_number: 7,
      section_title: "Economics: Development",
      question_type_refined: "true_or_false",
    }),
    makeDemoQuestion({
      question_id: "soc10_009",
      question: "9. Why did Mahatma Gandhi withdraw the Non-Cooperation Movement?",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Non-Cooperation Movement",
      unit_number: 1,
      section_title: "History: Nationalism in India",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_010",
      question: "10. Mention any two effects of the Great Depression on the Indian economy.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Global economy",
      unit_number: 2,
      section_title: "History: The Making of a Global World",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_011",
      question: "11. What is resource planning? Why is it important?",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "understand",
      topic: "Resource planning",
      unit_number: 3,
      section_title: "Geography: Resources and Development",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_012",
      question: "12. Give two reasons for land degradation in India.",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "remember",
      topic: "Land resources",
      unit_number: 3,
      section_title: "Geography: Resources and Development",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_013",
      question: "13. Explain any two features of federalism.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Federalism",
      unit_number: 4,
      section_title: "Civics: Federalism",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_014",
      question: "14. Why is decentralisation important in a democracy?",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "analyze",
      topic: "Local self-government",
      unit_number: 4,
      section_title: "Civics: Federalism",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_015",
      question: "15. Distinguish between organised and unorganised sectors.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "analyze",
      topic: "Sectors of economy",
      unit_number: 5,
      section_title: "Economics: Sectors of the Indian Economy",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_016",
      question: "16. How do banks mediate between depositors and borrowers?",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "understand",
      topic: "Money and credit",
      unit_number: 6,
      section_title: "Economics: Money and Credit",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_017",
      question: "17. Mention any two positive effects of globalisation on Indian consumers.",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "understand",
      topic: "Globalisation",
      unit_number: 7,
      section_title: "Economics: Globalisation",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_018",
      question: "18. What is sustainable development? Give one example.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "understand",
      topic: "Development",
      unit_number: 7,
      section_title: "Economics: Development",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_019",
      question: "19. Compare intensive subsistence farming with commercial farming.",
      marks: 2,
      type: "short_answer",
      difficulty: "medium",
      bloom_level: "analyze",
      topic: "Agriculture",
      unit_number: 3,
      section_title: "Geography: Agriculture",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_020",
      question: "20. What role do political parties play in a democracy?",
      marks: 2,
      type: "short_answer",
      difficulty: "easy",
      bloom_level: "understand",
      topic: "Political parties",
      unit_number: 4,
      section_title: "Civics: Political Parties",
      question_type_refined: "short_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_021",
      question: "21. Explain the causes and impact of the Civil Disobedience Movement in India.",
      marks: 5,
      type: "long_answer",
      difficulty: "hard",
      bloom_level: "analyze",
      topic: "Civil Disobedience Movement",
      unit_number: 1,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_022",
      question: "22. Describe the main features of Indian agriculture and explain the major challenges faced by farmers.",
      marks: 5,
      type: "long_answer",
      difficulty: "medium",
      bloom_level: "analyze",
      topic: "Agriculture",
      unit_number: 3,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_023",
      question: "23. Explain how power sharing strengthens democracy. Support your answer with examples.",
      marks: 5,
      type: "long_answer",
      difficulty: "hard",
      bloom_level: "evaluate",
      topic: "Power sharing",
      unit_number: 4,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_024",
      question: "24. Analyse the contribution of the tertiary sector to the Indian economy.",
      marks: 5,
      type: "long_answer",
      difficulty: "medium",
      bloom_level: "analyze",
      topic: "Sectors of economy",
      unit_number: 5,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
    makeDemoQuestion({
      question_id: "soc10_025",
      question: "25. Explain the role of money and credit in daily economic activities. Why should credit be available at reasonable rates?",
      marks: 5,
      type: "long_answer",
      difficulty: "hard",
      bloom_level: "evaluate",
      topic: "Money and credit",
      unit_number: 6,
      section_title: "Answer in detail.",
      question_type_refined: "long_answer",
    }),
  ],
};
