import { useState } from "react";
import { AnalysisReport } from "./UIComponents";

interface ResultsProps { result: any; onNew: () => void; }

export function ResultsScreen({ result, onNew }: ResultsProps) {
  const [showAnalysis, setShowAnalysis] = useState(false);

  function handleDownloadRec() {
    const fname = `debatearena-${(result.topic || "session").slice(0, 22).replace(/\s+/g, "-")}.webm`;
    result.recorder?.download(fname);
  }

  function handleDownloadAnalysis() {
    const rpt = `DebateArena Analysis Report\n\nTopic: ${result.topic}\nMode: ${result.mode}${result.subMode ? ` (${result.subMode})` : ""}\nDuration: ${result.timer}\nParticipants: ${result.participants}\n\nGenerated by DebateArena`;
    const b = new Blob([rpt], { type: "text/plain" });
    const u = URL.createObjectURL(b);
    const a = document.createElement("a"); a.href = u; a.download = "debatearena-analysis.txt"; a.click();
    URL.revokeObjectURL(u);
  }

  const emoji = result.mode === "debate" ? "⚔️" : result.mode === "seminar" ? "🎓" : "📹";
  const title = result.mode === "debate" ? "Debate Complete!" : result.mode === "seminar" ? "Seminar Complete!" : "Meeting Ended!";
  const showAnalysisBtn = result.mode === "debate" || result.mode === "seminar";

  return (
    <div className="results-page">
      <div className="res-trophy">{result.mode === "debate" ? "🏆" : result.mode === "seminar" ? "🎓" : "✅"}</div>
      <h2 className="res-title">{title}</h2>
      <p className="res-sub">
        {emoji} Session lasted <strong style={{ color: "var(--ind)" }}>{result.timer}</strong> with <strong>{result.participants}</strong> participant(s).
        {result.syncedToCalendar && <> 📅 <span style={{ color: "var(--em)" }}>Saved to Calendar.</span></>}
      </p>

      <div className="res-stats">
        {[
          { l: "Duration",     v: result.timer,       i: "⏱️" },
          { l: "Participants", v: result.participants, i: "👥" },
          { l: "Exchanges",    v: 14,                 i: "💬" },
        ].map((s, i) => (
          <div key={s.l} className="res-stat" style={{ animationDelay: `${i * 0.1}s` }}>
            <div className="res-stat-ico">{s.i}</div>
            <div className="res-stat-val">{s.v}</div>
            <div className="res-stat-lbl">{s.l}</div>
          </div>
        ))}
      </div>

      <div className="res-actions">
        {result.hasRecording && (
          <button className="btn-s" style={{ display: "flex", alignItems: "center", gap: 7, justifyContent: "center" }} onClick={handleDownloadRec}>
            📥 Download Recording
          </button>
        )}
        {showAnalysisBtn && (
          <button className="btn-s" style={{ display: "flex", alignItems: "center", gap: 7, justifyContent: "center", borderColor: "rgba(91,94,244,.3)", color: "var(--ind)" }} onClick={() => setShowAnalysis(true)}>
            📊 View Analysis Report
          </button>
        )}
        <button className="btn-p" style={{ fontSize: 13.5 }} onClick={onNew}>Start New Session</button>
      </div>

      {showAnalysis && (
        <AnalysisReport
          mode={result.mode} subMode={result.subMode} topic={result.topic}
          participants={result.participantsList || [{ id: 0, name: "You" }, { id: 1, name: "Participant" }]}
          scores={result.scores || { you: 65, ai: 52 }} timer={result.timer}
          onClose={() => setShowAnalysis(false)} onDownload={handleDownloadAnalysis}
        />
      )}
    </div>
  );
}