export { ParallaxProvider } from "./ParallaxContext";
export { default as ParallaxLayer } from "./ParallaxLayer";
export { default as FeatureCard } from "./FeatureCard";
export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Features } from "./Features";
export { default as Testimonials } from "./Testimonials";
export { default as Pricing } from "./Pricing";
export { default as CTA } from "./CTA";
export { default as Footer } from "./Footer";
